<?php
/**
 * @file
 * Drupal Module: D7 Node
 *
 * By http://reyero.net
 */

use Drupal\d7taxonomy\TaxonomyManager;

/**
 * Get taxonomy_term object of the right type.
 *
 * @param $object
 *   Object, bundle name or NULL.
 *
 * @return Entity
 *   Object wrapping the given entity.
 */
function d7taxonomy_term_object($object) {
  return d7entity_object('taxonomy_term', $object);
}

/**
 * Implements hook_entity_info_alter().
 */
function d7taxonomy_entity_info_alter(&$entity_info) {
  $entity_info['taxonomy_term']['controller class'] = '\Drupal\d7taxonomy\TaxonomyTermController';
}

/**
 * Implements hook_taxonomy_term_delete()
 */
function d7taxonomy_taxonomy_term_delete($term) {
  TaxonomyManager::hook_taxonomy_term_delete($term);
}

/**
 * Implements hook_taxonomy_term_insert()
 */
function d7taxonomy_taxonomy_term_insert($term) {
  TaxonomyManager::hook_taxonomy_term_insert($term);
}

/**
 * Implements hook_taxonomy_term_load()
 */
function d7taxonomy_taxonomy_term_load($terms) {
  TaxonomyManager::hook_taxonomy_term_load($terms);
}

/**
 * Implements hook_taxonomy_term_presave()
 */
function d7taxonomy_taxonomy_term_presave($term) {
  TaxonomyManager::hook_taxonomy_term_presave($term);
}

/**
 * Implements hook_taxonomy_term_update()
 */
function d7taxonomy_taxonomy_term_update($term) {
  TaxonomyManager::hook_taxonomy_term_update($term);
}

/**
 * Implements hook_taxonomy_term_view()
 */
function d7taxonomy_taxonomy_term_view($term, $view_mode, $langcode) {
  TaxonomyManager::hook_taxonomy_term_view($term, $view_mode, $langcode);
}

/**
 * Implements hook_taxonomy_term_view_alter()
 */
function d7taxonomy_taxonomy_term_view_alter(&$build) {
  TaxonomyManager::hook_taxonomy_term_view_alter($build);
}

/**
 * Implements hook_preprocess_HOOK
 */
function d7taxonomy_preprocess_taxonomy_term(&$variables) {
  TaxonomyManager::hook_preprocess_taxonomy_term($variables);
}
